helmCharts:
- name: kube-prometheus-stack
  repo: https://prometheus-community.github.io/helm-charts
  version: 43.2.1
  releaseName: prom-operator
  namespace: default
  valuesInline:
    commonLabels:
      sample: "values"
