apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
  - secrets

helmCharts:
- name: prometheus
  repo: https://prometheus-community.github.io/helm-charts
  version: 22.6.7
  releaseName: prom-operator
  namespace: prometheus-with-kustomize
  valuesFile: values/tst-values.yaml
  valuesInline:
    commonLabels:
      sample: "values"
