helmCharts:
- name: prometheus
  repo: https://prometheus-community.github.io/helm-charts
  version: 22.6.7
  releaseName: prom-operator
  namespace: prometheus-with-kustomize
  valuesInline:
    commonLabels:
      sample: "values"
